# Numpy


In [ ]:
import numpy as np


In [ ]:
l = [10,20,30]
l*2

In [ ]:
arr = np.array(l)
arr*2

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[-1])



In [ ]:
l = [10,23,34,43,432,234,533]
print(l)
print(type(l))

arr = np.array(l)
print(arr)
print(type(arr))

In [ ]:
#change value
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)

In [ ]:
arr = np.array(l)
arr[0] = 250
arr[-1] = 300
print(arr)

In [ ]:
#value add = 2
l = [10,20,30,40]
print(l+2)
arr = np.array(l)
print(arr+2)


In [ ]:
arr = np.arange(5) # start , stop , jump
print(arr)

In [ ]:
for i in range(1,5):
    print(i)

In [ ]:
arr = np.arange(1,10,2) # start , stop , jump
print(arr)

In [ ]:
l = [[1,2,3],[4,5,6]]
arr = np.array(l)
print(arr)
print(arr[0][0])

In [ ]:
#for numpy | array

In [ ]:
import numpy as np
import time
#for list
start = time.time()
sum1 = 0
for i in range(100000):
    sum1 += i*2
end = time.time()
print("for list", sum1,end-start)# more time to exicute list
#for numpy | array (array work every element | element wise)
start1 = time.time()
sum2 = 0
arr = np.arange(100000)*2
sum2 = arr.sum()
end1 = time.time()
print("for array:",sum2,end1-start1) # less time to exicute numpy

In [ ]:
arr = np.zeros(5)
print(arr)

arr1 = np.zeros((2,3))
print(arr1)

In [ ]:
arr = np.ones(5)
print(arr)

arr1 = np.ones((3,3))
print(arr1)

In [ ]:
arr = np.full((5),7)
print(arr)


arr1 = np.full((5,3),7)
print(arr1)

In [ ]:
arr = np.arange(6)
print(arr)

arr1 = arr.reshape(2,3)
print(arr1)

print(arr1.flatten())

In [ ]:
arr = np.arange(6).reshape(2,3)
print(arr)

print(arr.ravel())

In [ ]:
# flatten | copy
import numpy as np
# 2d
arr = np.arange(6)
arr1 = arr.reshape(2,3)
print(arr1)
# flatten
arr_new = arr1.flatten()
arr_new[0] = 100
print(arr1)
 

In [ ]:
# ravel | original
import numpy as np
# 2d
arr = np.arange(6).reshape(2,3)
print(arr)
# ravel
arr_new1 = arr.ravel()
arr_new1[0] = 200
print(arr)
 

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

arr1 = arr.transpose()
print(arr1)

arr1 = arr.T
print(arr1)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4]) # slicing
print(arr[-1])
print(arr[:])
print(arr[0:3:2]) # start from 0 to 3 and jump 1
print(arr[::2]) # jump by one
print(arr[::-1]) # reverse
print(arr[-2:])
print(arr[3:5])
 

In [ ]:
#2d 
arra = np.array([[1,2,3],[4,5,6]])
print(arra)
print(arra[0:2]) #row
print(arra[:,0]) # all rows | cols 0
print(arra[0,0])
print(arra[:,(1,1)])
print(arra[:,0:1])

In [ ]:
#for loop on numpy
arr = np.array([[10,20],[30,40],[50,60]])
print(arr)
for i in arr:
    print(i)
print(arr[[0,1,2],[1,1,0]])

In [ ]:
import numpy as np
 
arr = np.array([
    [2453,   75, 183975],
    [5795,   99, 573705],
    [4100,   36, 147600],
    [7526,   86, 647236],
    [9528,   45, 428760],
    [10788,  17, 183396]
])
print(arr)
print(arr[4:,1])
print(arr[:,(0)])

In [ ]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
print(arr.ndim) # 3d
print(arr[0,0])
print(arr[1,1,0])

print(arr[0:1,1])
print(arr[:,:,0])
 

In [ ]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],
     [3,4]
    ],
    [[5,6],
     [7,8]
    ]
    ])
# print(arr.ndim) # 3d
# print("=>",arr[0]) # block
# print("=>>",arr[0,0]) # block -> row
# print("=>>>",arr[0,0,0]) # block -> row -> cols
#
print(arr[:,0]) # all block -> row -> 0
print(arr[:,:,0]) # all block -> all rows -> cols 0
 

In [ ]:
import numpy as np
arr = np.array([10,35,40,7,15,20])
print(arr)
print(np.sort(arr)) # ascending
print(np.sort(arr)[::-1]) # decending
 
# 2d
arr1 = arr.reshape(2,3)
print(arr1)
print(np.sort(arr1))

In [ ]:
#filter
arr = np.array([10,20,30,40])
print(np.where(arr>20,arr*2,arr))

In [ ]:
import numpy as np
arr = np.array([4,5,8,10,20,12,15,17,19,30,23])
arr_f = arr[(arr > 10) & (arr < 20) ]
print(arr_f)
 

In [ ]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr != 6]
print(arr_f)
 
# example and opr 10 se 20 between
arr1 = np.array([5,6,7,8,11,24,16,19,25])
arr_f1 = arr1[(arr1>10) & (arr1<20)]
print(arr_f1)
 

In [ ]:
arr = np.array([10,20,3,4,14,15,16,90,100])
print(arr)
arr_w = np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)

In [ ]:
arr1 = np.array([[10, 20, 30],

                 [40, 50, 60]])
 
arr2 = np.array([[1, 2, 3],

                 [4, 5, 6]])
 
arr1_arr2 = np.concatenate((arr1, arr2), axis=0)

print(arr1_arr2)
 

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[7,8,9],[10,11,12]])
result =np.hstack((arr,arr1))
result2 = np.vstack((arr,arr1))
print(result)
print(result2)

In [ ]:
import numpy as np
from scipy import stats

arr = np.array([2,2,3,4,4,4,5])

result = stats.mode(arr)

print("Mode :", result.mode)
print("Frequency :", result.count)

In [ ]:
# np.sum(a) -> Sum of all elements
# np.mean(a) -> Average = Sum of elements / Number of elements
# np.median(a) -> Middle value after sorting
# np.min(a) -> Smallest value in array
# np.max(a) -> Largest value in array
# np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
# np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
# np.prod(a) -> Multiplication of all elements
# np.cumsum(a) -> Cumulative (running) sum
# np.cumprod(a) -> Cumulative (running) product
# np.argmin(a) -> Index position of minimum value
# np.argmax(a) -> Index position of maximum value
# np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
# np.unique(a) -> Returns unique values only -> Removes duplicates
# np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
# np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
# np.ptp(a) -> Range = Max - Min
# np.any(a) -> True if at least one value is True
 

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])

sum = np.sum(arr)
print(sum)

mean = np.mean(arr)
print(mean)

median = np.median(arr)
print(median)

min = np.min(arr)
print(min)

max = np.max(arr)
print(max)

var = np.var(arr)
print(var)

std = np.std(arr)
print(std)

product = np.prod(arr)
print(product)

cumsum = np.cumsum(arr)
print(cumsum)

arrange = np.arange(10)
print(arrange)

arrange10 = np.argmax(arr)
print(arrange10)

module = np.abs(arr)
print(module)

unique = np.unique(arr)
print(unique)

perc = np.percentile(arr, 50)
print(perc)

quant = np.quantile(arr, 0.1)
print(quant)

range = np.ptp(arr)
print(range)

any = np.any(arr)
print(any)

# Handling missing value

In [ ]:
import numpy as np
arr = np.array([10,20,np.nan,30,40])
print(arr)
#isnan
print(np.isnan(arr))

In [ ]:
import numpy as np
arr = np.array([10,20,np.nan,30,40])
print(arr)
#isnan
print(np.isnan(arr))

**Questions:-**

1. Print the complete dataset
1. Find the shape of the array.
1. Find the number of dimensions.
1. Find the total number of elements.
1. Print only Restaurant IDs.
1. Print 2021 sales data.
1. Print 2024 sales data
1. Find the maximum sales value
1. Find the minimum sales value.
1. Find total sales of all restaurants in 2021.
1. Find average sales in 2024.
1. Find total sales of each restaurant.
1. Find average sales of each restaurant.

In [2]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
import numpy as np

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print(sales_data)
print(sales_data.shape)
print("Dimensions:", sales_data.ndim)
print("Total Elements:", sales_data.size)
print("restaurant_id: ",sales_data[:,0])
print("2021 sales: ",sales_data[:,1])
print("2024 sales: ",sales_data[:,4])
print(np.max(sales_data[:,1:]))
print(np.min(sales_data[:,1:]))
print("\nTotal 2021 Sales:", np.sum(sales_data[:, 1]))
print("Average 2024 Sales:", np.mean(sales_data[:, 4]))
print(np.sum(sales_data[:,1:],axis = 1))
print(np.mean(sales_data[:, 1:], axis=1))


[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
Dimensions: 2
Total Elements: 25
restaurant_id:  [1 2 3 4 5]
2021 sales:  [150000 120000 200000 180000 160000]
2024 sales:  [250000 190000 300000 270000 230000]
300000
120000

Total 2021 Sales: 810000
Average 2024 Sales: 248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]
